import { useEffect, useState, type FormEvent } from 'react';
import type { AdminAccountSummary, AdminPage, AdminSummary } from '../../../contracts/admin.ts';
import { Avatar, Emblem, Field, Modal, Notice, PageHeading } from '../components/ui.tsx';
import { ApiFailure, errorMessage, request } from '../transport/http.ts';
import { newRequestId } from '../transport/ids.ts';

type Editor = { kind: 'nickname' | 'password' | 'delete'; account: AdminAccountSummary } | null;
const pageSize = 25, dateTime = (value: number | null) => value === null ? '—' : new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(value);
const adminError = (error: unknown) => error instanceof ApiFailure && error.code === 'account_in_active_game' ? '账号仍关联进行中的对局，暂不能修改昵称或永久删除。' : errorMessage(error);

export function AdminApp() {
  const [mode, setMode] = useState<'loading'|'disabled'|'login'|'ready'>('loading'), [password, setPassword] = useState(''), [busy, setBusy] = useState(false), [failure, setFailure] = useState('');
  const [tab, setTab] = useState<'overview'|'accounts'|'settings'>('overview'), [summary, setSummary] = useState<AdminSummary|null>(null), [accounts, setAccounts] = useState<AdminPage<AdminAccountSummary>|null>(null);
  const [query, setQuery] = useState(''), [status, setStatus] = useState('all'), [page, setPage] = useState(1), [editor, setEditor] = useState<Editor>(null), [value, setValue] = useState(''), [confirmValue, setConfirmValue] = useState(''), [confirmation, setConfirmation] = useState<{title:string;description:string;path:string}|null>(null);
  const load = async () => { const [s,a] = await Promise.all([request<AdminSummary>('/admin/summary'), request<AdminPage<AdminAccountSummary>>(`/admin/accounts?query=${encodeURIComponent(query)}&status=${status}&page=${page}&pageSize=${pageSize}`)]); setSummary(s); setAccounts(a); setFailure(''); };
  useEffect(() => { void request('/admin/me').then(() => { setMode('ready'); return load(); }).catch(error => { if (error instanceof ApiFailure && error.code === 'admin_not_configured') setMode('disabled'); else setMode('login'); }); }, []);
  useEffect(() => { if (mode === 'ready') void load().catch(error => setFailure(adminError(error))); }, [page,status]);
  const mutate = async <T,>(path:string, body:Record<string,unknown>={}, method:'POST'|'PATCH'='POST', reload=true) => { setBusy(true); setFailure(''); try { const result=await request<T>(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,requestId:newRequestId()})}); if(reload) await load(); return result; } catch(error){setFailure(adminError(error)); return null;} finally{setBusy(false);} };
  const login = async (event:FormEvent) => { event.preventDefault(); setBusy(true); try { await request('/admin/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}); setPassword(''); setMode('ready'); await load(); } catch(error){setFailure(adminError(error));} finally{setBusy(false);} };
  if(mode==='loading') return <main className="splash"><Emblem/><h1>剧院管理</h1><p>正在确认管理员配置…</p></main>;
  if(mode==='disabled') return <main className="splash"><Emblem/><h1>剧院管理</h1><Notice error>管理员功能尚未配置。</Notice><a className="button" href="/">返回玩家入口</a></main>;
  if(mode==='login') return <main className="admin-login"><form className="auth-card panel" onSubmit={login}><Emblem/><h1>剧院管理</h1>{failure&&<Notice error>{failure}</Notice>}<Field label="管理员密码" type="password" value={password} onChange={event=>setPassword(event.target.value)} required/><button className="button button--primary button--wide">进入管理台</button></form></main>;
  const saveEditor = async () => { if(!editor)return; if(editor.kind==='nickname') { const result=await mutate<{nickname:string;profileVersion:number}>(`/admin/accounts/${editor.account.userId}`,{nickname:value},'PATCH',false); if(result){setQuery(result.nickname);setAccounts(current=>current?{...current,items:current.items.map(item=>item.userId===editor.account.userId?{...item,nickname:result.nickname,profileVersion:result.profileVersion}:item)}:current);setEditor(null);} } else if(editor.kind==='password') { if(value!==confirmValue){setFailure('两次输入的新密码不一致。');return;} const result=await mutate(`/admin/accounts/${editor.account.userId}/reset-password`,{password:value},'POST',false); if(result){setAccounts(current=>current?{...current,items:current.items.map(item=>item.userId===editor.account.userId?{...item,activeSessionCount:0}:item)}:current);setEditor(null);} } else { const result=await mutate(`/admin/accounts/${editor.account.userId}/delete`); if(result)setEditor(null); } };
  return <main className="admin-layout"><aside className="navigation"><div className="brand"><Emblem/><span>剧院管理</span></div><nav>{(['overview','accounts','settings'] as const).map(key=><button key={key} className={`nav-item ${tab===key?'active':''}`} onClick={()=>setTab(key)}>{key==='overview'?'概览':key==='accounts'?'账户':'注册设置'}</button>)}</nav><div className="nav-profile"><button className="text-button" disabled={busy} onClick={()=>void request('/admin/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).finally(()=>{setSummary(null);setAccounts(null);setMode('login');})}>退出管理</button><a className="text-button" href="/">玩家入口</a></div></aside><section className="home-main admin-main">
    {failure&&<Notice error>{failure}</Notice>}
    {tab==='overview'&&<><PageHeading eyebrow="ADMIN OVERVIEW" title="资源概览">账号与注册状态。</PageHeading>{summary&&<div className="admin-stats"><article><strong>{summary.accounts.total}</strong><span>账户</span></article><article><strong>{summary.accounts.activeSessions}</strong><span>活跃会话</span></article><article><strong>{summary.registrationEnabled?'开放':'关闭'}</strong><span>新用户注册</span></article><article><strong>{summary.avatars.referenced}</strong><span>在用头像</span></article></div>}</>}
    {tab==='settings'&&<><PageHeading eyebrow="REGISTRATION" title="注册设置">关闭后已有账号仍可登录。</PageHeading><section className="panel setting-row"><div><strong>允许新用户注册</strong><p className="muted">提交注册时服务端会再次检查。</p></div><button className={`button ${summary?.registrationEnabled?'button--danger':'button--primary'}`} disabled={busy} onClick={()=>void mutate('/admin/settings',{registrationEnabled:!summary?.registrationEnabled},'PATCH')}>{summary?.registrationEnabled?'停止注册':'开放注册'}</button></section></>}
    {tab==='accounts'&&<><PageHeading eyebrow="ACCOUNT DIRECTORY" title="账户管理">按数字UID或昵称搜索。</PageHeading><form className="admin-filters" onSubmit={event=>{event.preventDefault();setPage(1);void load();}}><Field label="搜索" value={query} onChange={event=>setQuery(event.target.value)} placeholder="UID或昵称"/><select value={status} onChange={event=>{setStatus(event.target.value);setPage(1);}}><option value="all">全部</option><option value="active">可登录</option><option value="disabled">已停用</option></select><button className="button">搜索</button></form><div className="admin-card-list">{accounts?.items.map(account=><article className="panel admin-account" key={account.userId}><Avatar url={account.avatarUrl} name={account.nickname}/><div className="admin-account__body"><h2>{account.nickname}</h2><p className="muted">UID {account.uid} · {account.status==='disabled'?'已停用':'可登录'} · {account.activeSessionCount}个会话<br/>{account.room?`房间 ${account.room.roomCode} · ${account.room.phase}`:'当前没有房间'} · 创建于 {dateTime(account.createdAt)}</p><div className="button-row"><button className="button" disabled={busy||account.room?.phase==='playing'} onClick={()=>{setEditor({kind:'nickname',account});setValue(account.nickname);}}>改昵称</button><button className="button" onClick={()=>{setEditor({kind:'password',account});setValue('');setConfirmValue('');}}>设置新密码</button><button className="button" onClick={()=>setConfirmation({title:account.status==='active'?'停用账户？':'重新启用账户？',description:'会撤销该账号现有会话。',path:`/admin/accounts/${account.userId}/${account.status==='active'?'disable':'enable'}`})}>{account.status==='active'?'停用':'启用'}</button><button className="button button--danger" disabled={!account.deletable} title={account.deleteReason??''} onClick={()=>{setEditor({kind:'delete',account});setValue('');}}>永久删除</button></div></div></article>)}</div>{accounts&&<Pagination page={page} total={accounts.total} setPage={setPage}/>}</>}
  </section>
  {confirmation&&<Modal title={confirmation.title} onClose={()=>setConfirmation(null)}><p>{confirmation.description}</p><button className="button button--primary" onClick={()=>{const path=confirmation.path;setConfirmation(null);void mutate(path);}}>确认操作</button></Modal>}
  {editor&&<Modal title={editor.kind==='nickname'?'修改昵称':editor.kind==='password'?'设置新密码':'永久删除账号'} onClose={()=>setEditor(null)} dismissible={!busy}>{editor.kind==='delete'?<p>将永久删除 UID {editor.account.uid} 的登录账号与会话。完成对局历史会保留当局昵称，此操作不可恢复。</p>:<><Field label={editor.kind==='nickname'?'新昵称':'新密码'} type={editor.kind==='password'?'password':'text'} value={value} onChange={event=>setValue(event.target.value)} minLength={editor.kind==='nickname'?2:8} maxLength={editor.kind==='nickname'?32:16}/>{editor.kind==='password'&&<Field label="确认新密码" type="password" value={confirmValue} onChange={event=>setConfirmValue(event.target.value)} minLength={8} maxLength={16}/>}</>}<div className="button-row"><button className="button" onClick={()=>setEditor(null)}>取消</button><button className={`button ${editor.kind==='delete'?'button--danger':'button--primary'}`} disabled={busy} onClick={()=>void saveEditor()}>确认操作</button></div></Modal>}
  </main>;
}

function Pagination({page,total,setPage}:{page:number;total:number;setPage:(page:number)=>void}) { const pages=Math.max(1,Math.ceil(total/pageSize)); return <div className="pagination"><button className="button" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><span>第 {page} / {pages} 页 · 共 {total} 项</span><button className="button" disabled={page>=pages} onClick={()=>setPage(page+1)}>下一页</button></div>; }
